### ISSUE TITLE
Notes on producing several units over a week.

### ISSUE THREAD

**Issue by shreshthmohan** [Absurd-Industries/lampy#3]
## Log

- [We had already visited SP road](https://github.com/Absurd-Industries/lampy/issues/2) to source copper pipes of different dimensions and screws
- Amit and I had been coordinating for start producing for the upcoming 10 unit order by dev folio for one of their events.
- So Amit placed orders for USB cables, copper pipes, spools of 3d printing filament
- I crashed at Amit's for 2 days and 1 night to help with the production.
- I designed and got a thing printed from Printo to go on the packaging (spend more than the time needed because HSR printo's main printer broke. went to kora printo to get the print done)
- The USB cable order got delayed. So we had to go hunting for them in local shops. And Amit has specific constraints about buying indian-made cables. Ambrane and ERD are two known manufacturers, but we could not find enough for the order. Had to settle with boat.
- The local shop we ordered the stuff from did not have enough stock for the thing. So it took up headspace and a lot of back and forth before we got all the items in our order
- Got into production mode. I cut, deburred and sanded copper tubes. Amit later had problems inserting the plug because for some of the pipes the inner diameter was smaller.

## Issues
- Having the right copper tube length affects the thing. Too long and it affects the shadows on the top with the current shade. Too short and the 72 LEDs don't fit. 
- [ ]  Need to measure the temps of the copper tube and figure out if the normal wire used in the JST or 

### Design
- Diagonally places holes in the base cavity with chamfers
- Chamfers/fillet on the top of the tube plug
- More space for the coaxial cable sticking out from the back

### New design
- thicker copper tube
- smaller plastic mount that's completely hidden inside the shade and only the wooden coaster is visible
- use embedded swift to flash the thing
- better airflow from below

### Developer experience
- I particularly don't like how cumbersome it is to flash the MCU. Purav's process did not have the need to do it.

## Tasks
- [ ] Raise an invoice for the additional USB adapters provided with the lamps on devfolio's order
- [ ] Come up with a name for each shade design and have the step/stl files available (with dimensions)
- [ ] Make notes about different 3d printing filaments used over the course of developing different parts and versions of lampy. @layogtima 
- [ ] Diagonally places holes in the base cavity with chamfers (@shreshthmohan can do this in fusion)
- [ ] Chamfers/fillet on the top of the tube plug (@shreshthmohan can do this in fusion)
- [ ] More space for the coaxial cable sticking out from the back (@shreshthmohan can do this in fusion)
- [ ] Print cards with design and QR to product page to go with the box

## Things I don't like right now
- Having to plug and unplug the thing to change modes (several others have had the same annoyance)
- Cutting off the existing connector on the neopixel strip and then attaching new ones

**Comment by shreshthmohan** [comment]
## Highlights
- Sourcing issues (stuff not getting delivered in time)
- Material inconsistency (copper tubes inner dia, length)
-
